export const building = [
  {
    id: 1,
    buildingId: "B001",
    buildingNumber: "014453-48743",
    buildingType: "업무시설",
    buildingName: "비즈니스센터 A동",
    buildingCompletionDate: "2020-01-10",
    expirationDate: "2023-12-31",
    buildingOwner: "김병만",
    safetyInspection: "Y",
    reinforcementAndMaintenance: "Y",
    postNumber: "658-9632-001",
    buildingAddress: "시티빌123번가,메인스트리트",
    buildingDetailAddress: "예시 상세 주소 1",
    designPeriodStart: "2018-01-10",
    designPeriodEnd: "2018-04-10",
    designer: "TSM",
    constructionSupervisor: "존스미스",
    constructionPeriodStart: "2018-01-10",
    constructionPeriodEnd: "2018-03-10",
    construct: "TSM건설",
    totalConstructionCost: "1,000,000달러",
    supervisionPeriodStart: "2018-01-11",
    supervisionPeriodEnd: "2018-02-11",
    inspector: "제인도우",
    constructionName: "알파프로젝트",
    constructionClient: "XYZ기업",
    bigo: "특이사항없음",
  },
  {
    id: 2,
    buildingId: "B002",
    buildingNumber: "014453-48743",
    buildingType: "산업시설",
    buildingName: "비즈니스센터 B동",
    buildingCompletionDate: "2020-10-10",
    expirationDate: "2023-12-31~2024-12-30",
    buildingOwner: "황명식",
    safetyInspection: "Y",
    reinforcementAndMaintenance: "Y",
    postNumber: "658-9632-001",
    buildingAddress: "파크레인456,중앙아비뉴",
    buildingDetailAddress: "예시 상세 주소 2",
    designPeriodStart: "2019-03-11",
    designPeriodEnd: "2019-07-11",
    designer: "TSM",
    constructionSupervisor: "마리아존슨",
    constructionPeriodStart: "2019-03-13",
    constructionPeriodEnd: "2019-06-13",
    construct: "TSM건설",
    totalConstructionCost: "800,000달러",
    supervisionPeriodStart: "2019-03-12",
    supervisionPeriodEnd: "2019-04-12",
    inspector: "로버트박스",
    constructionName: "베타프로젝트",
    constructionClient: "ABC기업",
    bigo: "특이사항없음",
  },
  {
    id: 3,
    buildingId: "B003",
    buildingNumber: "014453-48743",
    buildingType: "숙박시설",
    buildingName: "비즈니스센터 C동",
    buildingCompletionDate: "2020-10-10",
    expirationDate: "2023-12-08",
    buildingOwner: "황명식",
    safetyInspection: "Y",
    reinforcementAndMaintenance: "Y",
    postNumber: "658-9632-001",
    buildingAddress: "파크레인456,중앙아비뉴",
    buildingDetailAddress: "예시 상세 주소 3",
    designPeriodStart: "2019-03-11",
    designPeriodEnd: "2019-08-11",
    designer: "TSM",
    constructionSupervisor: "마리아존슨",
    constructionPeriodStart: "2019-03-16",
    constructionPeriodEnd: "2019-03-16",
    construct: "TSM건설",
    totalConstructionCost: "800,000달러",
    supervisionPeriodStart: "2019-03-19",
    supervisionPeriodEnd: "2019-07-19",
    inspector: "로버트박스",
    constructionName: "베타프로젝트",
    constructionClient: "ABC기업",
    bigo: "특이사항없음",
  },
  {
    id: 4,
    buildingId: "B004",
    buildingNumber: "014453-48743",
    buildingType: "업무시설",
    buildingName: "비즈니스센터 D동",
    buildingCompletionDate: "2020-10-10",
    expirationDate: "2023-12-31",
    buildingOwner: "황명식",
    safetyInspection: "Y",
    reinforcementAndMaintenance: "Y",
    postNumber: "658-9632-001",
    buildingAddress: "파크레인456,중앙아비뉴",
    buildingDetailAddress: "예시 상세 주소 4",
    designPeriodStart: "2019-03-15",
    designPeriodEnd: "2019-06-15",
    designer: "TSM",
    constructionSupervisor: "마리아존슨",
    constructionPeriodStart: "2019-03-15",
    constructionPeriodEnd: "2019-09-15",
    construct: "TSM건설",
    totalConstructionCost: "800,000달러",
    supervisionPeriodStart: "2019-03-15",
    supervisionPeriodEnd: "2019-5-15",
    inspector: "로버트박스",
    constructionName: "베타프로젝트",
    constructionClient: "ABC기업",
    bigo: "특이사항없음",
  },
  {
    id: 5,
    buildingId: "B005",
    buildingNumber: "014453-48743",
    buildingType: "업무시설",
    buildingName: "비즈니스센터 E동",
    buildingCompletionDate: "2020-10-10",
    expirationDate: "2023-12-31",
    buildingOwner: "황명식",
    safetyInspection: "Y",
    reinforcementAndMaintenance: "Y",
    postNumber: "658-9632-001",
    buildingAddress: "파크레인456,중앙아비뉴",
    buildingDetailAddress: "예시 상세 주소 5",
    designPeriodStart: "2019-03-15",
    designPeriodEnd: "2019-07-15",
    designer: "TSM",
    constructionSupervisor: "마리아존슨",
    constructionPeriodStart: "2019-03-15",
    constructionPeriodEnd: "2019-08-15",
    construct: "TSM건설",
    totalConstructionCost: "800,000달러",
    supervisionPeriodStart: "2019-03-15",
    supervisionPeriodEnd: "2019-04-15",
    inspector: "로버트박스",
    constructionName: "베타프로젝트",
    constructionClient: "ABC기업",
    bigo: "특이사항없음",
  },
];

export const buildingInfoObject = {
  id: "",
  buildingId: "",
  buildingNumber: "",
  buildingType: "",
  buildingName: "",
  buildingCompletionDate: "",
  expirationDate: "",
  buildingOwner: "",
  safetyInspection: "",
  reinforcementAndMaintenance: "",
  postNumber: "",
  buildingAddress: "",
  buildingDetailAddress: "",
  designPeriod: "",
  designer: "",
  constructionSupervisor: "",
  constructionPeriod: "",
  construct: "",
  totalConstructionCost: "",
  supervisionPeriod: "",
  inspector: "",
  constructionName: "",
  constructionClient: "",
  bigo: "",
};
