export const roll = [
  {
    id: "1",
    UserId: "ADMIN",
    GroupName: "관리자그룹",
    GroupInfo: "관리자그룹",
    bigo: "특이사항없음",
    use: "Y",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: "2",
    UserId: "ADMIN",
    GroupName: "관리자그룹",
    GroupInfo: "관리자그룹",
    bigo: "특이사항없음",
    use: "Y",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: "3",
    UserId: "BAS_USER",
    GroupName: "BAS 사용자 그룹",
    GroupInfo: "BAS 사용자 그룹",
    bigo: "특이사항없음",
    use: "Y",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: "4",
    UserId: "BAS_USER",
    GroupName: "BAS 사용자 그룹",
    GroupInfo: "BAS 사용자 그룹",
    bigo: "특이사항없음",
    use: "Y",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: "5",
    UserId: "BEMS_USER",
    GroupName: "BEMS 사용자 그룹",
    GroupInfo: "BEMS 사용자 그룹",
    bigo: "특이사항없음",
    use: "Y",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: "6",
    UserId: "BEMS_USER",
    GroupName: "BEMS 사용자 그룹",
    GroupInfo: "BEMS 사용자 그룹",
    bigo: "특이사항없음",
    use: "Y",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
];

export const rollObject = [
  {
    id: "",
    UserId: "",
    GroupName: "",
    GroupInfo: "",
    use: "",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
];
