export const products = [
  {
    id: 1,
    system: "공통",
    menuId: "NBSZ0000",
    menuName: "시스템관리",
    parentMenuId: "",
    parentMenuName: "",
    sorting: "1",
    MenuUrl: "",
    bigo: "",
    use: "Y",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
    roll: true,
    items: [
      {
        id: 2,
        system: "공통",
        menuId: "NBSZD0000",
        menuName: "프로그램관리",
        parentMenuId: "",
        parentMenuName: "",
        sorting: "1",
        MenuUrl: "",
        bigo: "",
        use: "N",
        creater: "관리자",
        createTime: "",
        updater: "",
        updateTime: "",
        roll: true,
        items: [
          {
            id: 11,
            system: "공통",
            menuId: "NBSZD010",
            menuName: "메뉴관리",
            parentId: "",
            parentMenuId: "",
            parentMenuName: "프로그램관리",
            sorting: "1",
            MenuUrl: "",
            bigo: "",
            use: "N",
            creater: "관리자",
            createTime: "",
            updater: "",
            updateTime: "",
            roll: true,
          },
          {
            id: 12,
            system: "공통",
            menuId: "NBSZD020",
            menuName: "권한그룹별메뉴관리",
            parentMenuId: "",
            parentMenuName: "프로그램관리",
            sorting: "1",
            MenuUrl: "",
            bigo: "",
            use: "Y",
            creater: "관리자",
            createTime: "",
            updater: "",
            updateTime: "",
            roll: true,
          },
        ],
      },
    ],
  },
];

export const TreeObject = {
  system: "",
  menuId: "",
  menuName: "",
  parentMenuId: "",
  parentMenuName: "",
  sorting: "",
  MenuUrl: "",
  bigo: "",
  use: "Y",
  creater: "",
  createTime: "",
  updater: "",
  updateTime: "",
  roll: 2,
};

export const SystemCheck = [
  {
    value: "BEMS",
    text: "BEMS",
  },
  {
    value: "BAS",
    text: "BAS",
  },
  {
    value: "공통",
    text: "Public",
  },
];

export const stateUse = [
  {
    id: 1,
    roll: true,
  },
  {
    ID: 2,
    roll: false,
  },
];

// export const products = [
//   {
//     menuId: "NBSZ0000",
//     menuName: "시스템관리",
//     Sorting: "1",
//     use: "Y",
//     creater: "관리자",
//     createTime: "",
//     updater: "",
//     updateTime: "",
//     items: [
//       {
//         items: [
//           {
//             menuId: "NBSZD010",
//             menuName: "메뉴관리",
//             Sorting: "2",
//             use: "Y",
//             creater: "관리자",
//             createTime: "",
//             updater: "",
//             updateTime: "",
//           },
//           {
//             menuId: "NBSZD020",
//             menuName: "권한그룹별메뉴관리",
//             Sorting: "3",
//             use: "Y",
//             creater: "관리자",
//             createTime: "",
//             updater: "",
//             updateTime: "",
//           },
//         ],
//         menuId: "NBSZD0000",
//         menuName: "프로그램관리",
//         Sorting: "4",
//         use: "Y",
//         creater: "관리자",
//         createTime: "",
//         updater: "",
//         updateTime: "",
//       },
//       {
//         items: [
//           {
//             country: "US",
//             haveCustomer: "N",
//             haveLinkNumber: "N",
//             id: 2720184468,
//             text: "Test Data - Level 2",
//             parentId: 2,
//           },
//           {
//             country: "US",
//             haveCustomer: "N",
//             haveLinkNumber: "N",
//             id: 2720188708,
//             text: "Test Data - Level 2",
//             parentId: 2,
//           },
//         ],
//         country: "US",
//         haveCustomer: "N",
//         haveLinkNumber: "N",
//         id: 2720185258,
//         text: "Test Data_Level 1",
//         parentId: 1,
//       },
//       {
//         items: [
//           {
//             country: "US",
//             haveCustomer: "N",
//             haveLinkNumber: "N",
//             id: 2720188408,
//             text: "Test Data_Level 2",
//             parentId: 1,
//           },
//           {
//             country: "US",
//             haveCustomer: "N",
//             haveLinkNumber: "N",
//             id: 2720180908,
//             text: "Test Data_Level 2",
//             parentId: 1,
//           },
//           {
//             items: [
//               {
//                 country: "US",
//                 haveCustomer: "N",
//                 haveLinkNumber: "N",
//                 id: 2720186188,
//                 text: "Test Data_Level 3",
//                 parentId: 1,
//               },
//               {
//                 country: "US",
//                 haveCustomer: "N",
//                 haveLinkNumber: "N",
//                 id: 2720182578,
//                 text: "Test Data_Level 3",
//                 parentId: 1,
//               },
//             ],
//             country: "US",
//             haveCustomer: "N",
//             haveLinkNumber: "N",
//             id: 2720186158,
//             text: "Test Data- Level 2",
//             parentId: 1,
//           },
//         ],
//         country: "US",
//         haveCustomer: "N",
//         haveLinkNumber: "N",
//         id: 2720187298,
//         text: "Test Data_Level 1",
//         parentId: 1,
//       },
//     ],
//   },
// ];

// export const TreeObject = {
//   haveCustomer: "",
//   haveLinkNumber: "",
//   id: 0,
//   parentId: 0,
//   text: "",
// };
