export const users = [
  {
    id: 1,
    UserId: "Admin",
    UserName: "김병만",
    password: "",
    Group: "개발부서",
    Rank: "팀장",
    Phone: "010-1111-2222",
    Tell: "053-256-1235",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 2,
    UserId: "meneger",
    UserName: "전재민",
    password: "",
    Group: "개발부서",
    Rank: "주임",
    Phone: "010-3456-9876",
    Tell: "031-4785-2304",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 3,
    UserId: "meneger",
    UserName: "강하림",
    password: "",
    Group: "개발부서",
    Rank: "주임",
    Phone: "010-4567-2345",
    Tell: "031-3124-2354",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 4,
    UserId: "meneger",
    UserName: "백광현",
    password: "",
    Group: "개발부서",
    Rank: "주임",
    Phone: "010-1111-2222",
    Tell: "031-764-9876",
    Email: "tsm@tsmech.co.kr",
    Use: "N",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 5,
    UserId: "meneger",
    UserName: "박경찬",
    password: "",
    Group: "개발부서",
    Rank: "대리",
    Phone: "010-4573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 6,
    UserId: "meneger",
    UserName: "최미소",
    password: "",
    Group: "경영지원실",
    Rank: "대리",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "N",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 7,
    UserId: "meneger",
    UserName: "안광인",
    password: "",
    Group: "비즈사업부",
    Rank: "대리",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 8,
    UserId: "meneger",
    UserName: "배현아",
    password: "",
    Group: "비즈사업부",
    Rank: "대리",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 9,
    UserId: "meneger",
    UserName: "서기원",
    password: "",
    Group: "시스템파트",
    Rank: "대리",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 10,
    UserId: "meneger",
    UserName: "염승호",
    password: "",
    Group: "시스템파트",
    Rank: "차장",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 11,
    UserId: "meneger",
    UserName: "이한솔",
    password: "",
    Group: "시스템파트",
    Rank: "대리",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 12,
    UserId: "Admin",
    UserName: "황명식",
    password: "",
    Group: "대표이사",
    Rank: "대표",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 13,
    UserId: "Admin",
    UserName: "송근",
    password: "",
    Group: "시스템파트",
    Rank: "전무",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 14,
    UserId: "meneger",
    UserName: "최미소",
    password: "",
    Group: "시스템파트",
    Rank: "대리",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
  {
    id: 15,
    UserId: "meneger",
    UserName: "임태준",
    password: "",
    Group: "경영지원실",
    Rank: "실장",
    Phone: "010-5573-0778",
    Tell: "031-457-5673",
    Email: "tsm@tsmech.co.kr",
    Use: "Y",
    Bigo: "특이사항없음",
    creater: "관리자",
    createTime: "",
    updater: "",
    updateTime: "",
  },
];

export const userObject = [
  {
    id: "",
    UserName: "",
    Group: "",
    Rank: "",
    Phone: "",
    Tell: "",
    Email: "",
    Use: "",
    Bigo: "",
    creater: "",
    createTime: "",
    updater: "",
    updateTime: "",
  },
];
